name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
    
      - uses: action/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Enviroment Information
        run: vercel pull --yes --enviroment=production --token=${{ secret.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secret.VERCEL_TOKEN }}

      - name: Deploy Proyect Artifacts
        run: vercel deploy --prebuild --prod --token=${{ secret.VERCEL_TOKEN }}